[package]
name = "geokit"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
itertools = "0.12.0"
regex = "1.10.2"

[dependencies]
smallvec = "1.11.2"
thiserror = "1.0.50"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
