[package]
name = "geokit"
version.workspace = true
edition.workspace = true

[dependencies]
nalgebra = { workspace = true }
num = { workspace = true }
smol_str = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
approx = { workspace = true }
regex = { workspace = true }
