[package]
name = "geokit"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
itertools = "0.12.0"
regex = "1.10.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
