[package]
name = "geokit"
version.workspace = true
edition.workspace = true

[dependencies]
dyn-clone = { workspace = true }
nalgebra = { workspace = true }
num = { workspace = true }
smallvec = { workspace = true }
smol_str = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
approx = { workspace = true }
regex = { workspace = true }
