[package]
name = "geokit"
version.workspace = true
edition.workspace = true

[dependencies]
dyn-clone = { workspace = true }
nalgebra = { workspace = true }
num = { workspace = true }
smol_str = { workspace = true }
thiserror = { workspace = true }
approx = { workspace = true }
derive_more = { workspace = true }

[dev-dependencies]
regex = { workspace = true }
