[package]
name = "geokit"
version.workspace = true
edition.workspace = true

[dependencies]
geomath = { path = "../geomath/" }
smallvec = "1.11.2"
thiserror = { workspace = true }
num = { workspace = true }
dyn-clone = "1.0.16"

[dev-dependencies]
itertools = "0.12.0"
regex = "1.10.2"
approx = { workspace = true }
